ktor:
    application:
        modules:
            - com.marketsmasher.ApplicationKt.module
    deployment:
        port: 8080
postgres:
  url: "jdbc:postgresql://localhost/default"
  user: username
  password: password
jwt:
  audience: "my-audience"
  issuer: "http://localhost"
  realm: "ktor sample app"
  secret: "qwerty"